import { execFile } from 'child_process';
import { mkdtemp, readFile, rm, writeFile } from 'fs/promises';
import os from 'os';
import path from 'path';
import { promisify } from 'util';
import sharp from 'sharp';
import { PrismaClient } from '@prisma/client';
import { StoredRemoteAsset, storageService } from './storage.service';

const execFileAsync = promisify(execFile);
const prisma = new PrismaClient();
const MAX_SOURCE_BYTES = 250 * 1024 * 1024;

async function download(sourceUrl: string): Promise<Buffer> {
  const response = await fetch(sourceUrl);
  if (!response.ok) throw new Error(`Thumbnail source download failed: ${response.status}`);
  const declaredSize = Number(response.headers.get('content-length') || 0);
  if (declaredSize > MAX_SOURCE_BYTES) throw new Error('Thumbnail source is too large');
  const buffer = Buffer.from(await response.arrayBuffer());
  if (buffer.byteLength > MAX_SOURCE_BYTES) throw new Error('Thumbnail source is too large');
  return buffer;
}

export async function createThumbnail(input: {
  sourceUrl: string;
  type: string;
  userId: string;
  assetId: string;
}): Promise<StoredRemoteAsset | null> {
  if (!storageService.isConfigured()) return null;
  const source = await download(input.sourceUrl);
  let thumbnail: Buffer;

  if (input.type === 'image') {
    thumbnail = await sharp(source)
      .rotate()
      .resize({ width: 640, height: 640, fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 78 })
      .toBuffer();
  } else {
    const directory = await mkdtemp(path.join(os.tmpdir(), 'marsfield-thumb-'));
    const inputPath = path.join(directory, 'source-video');
    const framePath = path.join(directory, 'frame.webp');
    try {
      await writeFile(inputPath, source);
      await execFileAsync('ffmpeg', [
        '-hide_banner', '-loglevel', 'error', '-y', '-ss', '0.5', '-i', inputPath,
        '-frames:v', '1', '-vf', "scale='min(640,iw)':-2", '-quality', '75', framePath,
      ], { timeout: 30_000 });
      thumbnail = await readFile(framePath);
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  }

  const stored = await storageService.storeBuffer({
    buffer: thumbnail,
    userId: input.userId,
    mimeType: 'image/webp',
    assetType: 'image',
    namespace: 'thumbnails',
    objectId: input.assetId,
    originalName: 'thumbnail.webp',
    metadata: { source: 'marsfield-thumbnail', assetId: input.assetId },
  });
  return stored;
}

export async function processThumbnailForAsset(assetId: string): Promise<boolean> {
  const asset = await prisma.asset.findUnique({
    where: { id: assetId },
    select: {
      id: true, userId: true, url: true, type: true, thumbnailUrl: true,
      thumbnailStorageObjectId: true,
    },
  });
  if (!asset?.userId || asset.thumbnailStorageObjectId) return false;

  // Direct image uploads use the original image as their preview and do not
  // need a separately stored derivative.
  if (asset.thumbnailUrl === asset.url) return false;

  // Adopt thumbnails generated by the previous synchronous implementation
  // without uploading or charging their bytes a second time.
  if (asset.thumbnailUrl) {
    const key = storageService.thumbnailKey(asset.userId, asset.id);
    const existing = await storageService.inspectObject(key);
    if (existing) {
      await prisma.$transaction(async (tx) => {
        const storageObject = await tx.storageObject.create({
          data: {
            userId: asset.userId,
            provider: 'cloudflare_r2',
            key,
            url: asset.thumbnailUrl!,
            mimeType: existing.mimeType || 'image/webp',
            byteSize: existing.byteSize,
          },
        });
        await tx.asset.update({
          where: { id: asset.id },
          data: { thumbnailStorageObjectId: storageObject.id },
        });
      });
      return true;
    }
  }

  const thumbnail = await createThumbnail({
    sourceUrl: asset.url,
    type: asset.type,
    userId: asset.userId,
    assetId: asset.id,
  });
  if (!thumbnail) throw new Error('Durable storage is not configured');

  await prisma.$transaction(async (tx) => {
    const current = await tx.asset.findUnique({
      where: { id: asset.id },
      select: { thumbnailStorageObjectId: true },
    });
    if (!current || current.thumbnailStorageObjectId) return;

    const storageObject = await tx.storageObject.create({
      data: {
        userId: asset.userId,
        provider: thumbnail.provider,
        bucket: thumbnail.bucket,
        key: thumbnail.key,
        url: thumbnail.url,
        mimeType: thumbnail.mimeType,
        byteSize: thumbnail.byteSize,
        checksum: thumbnail.checksum,
      },
    });
    await tx.asset.update({
      where: { id: asset.id },
      data: { thumbnailUrl: thumbnail.url, thumbnailStorageObjectId: storageObject.id },
    });
    await tx.user.update({
      where: { id: asset.userId! },
      data: { storageUsageBytes: { increment: thumbnail.byteSize } },
    });
  });
  return true;
}
