'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { useAuth } from '@/app/layout';

type Influencer = { id: string; name: string; profile: any; voiceProfile?: string; status: string; currentVersion: number; versions?: Array<{ imageUrl?: string }> };
type Product = { id: string; name: string; brandName?: string; description?: string; primaryStorageObjectId?: string };
type Scene = { id: string; index: number; title: string; durationSeconds: number; location: string; description: string; characterAction: string; expression?: string; wardrobe: string; cameraFraming: string; cameraMovement: string; lighting?: string; productVisible: boolean; dialogue?: string; voiceover?: string; onScreenText?: string; transition?: string };
type Storyboard = { id: string; version: number; scenesRevision: number; imageUrl: string; layout: string; visualStyle: string; prompt: string; approved: boolean; createdAt: string };
type VideoGeneration = { id: string; storyboardId: string; attempt: number; prompt: string; motionInstructions?: string; settings: any; videoUrl: string; approved: boolean; creditsUsed: number; createdAt: string };
type Project = { id: string; title: string; idea: string; status: string; durationSeconds: number; aspectRatio: string; scenesRevision?: number; influencerId: string; productId?: string; scenes?: Scene[]; storyboards?: Storyboard[]; videoGenerations?: VideoGeneration[]; influencer?: Influencer; product?: Product; _count?: { scenes: number } };
type GeneratedImage = { id: string; status: string; output_url?: string; error?: string };
type Tab = 'influencers' | 'products' | 'projects';

const field: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: '0.35rem', color: 'var(--foreground-muted)', fontSize: '0.78rem' };
const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))', gap: '0.8rem' };

export default function InfluencerStudioPage() {
  const { token } = useAuth();
  const [tab, setTab] = useState<Tab>('influencers');
  const [influencers, setInfluencers] = useState<Influencer[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [imageOwner, setImageOwner] = useState<string | null>(null);
  const [generatingFor, setGeneratingFor] = useState<string | null>(null);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    if (!token) return;
    try {
      const [nextInfluencers, nextProducts, nextProjects] = await Promise.all([api.getInfluencers(), api.getInfluencerProducts(), api.getInfluencerProjects()]);
      setInfluencers(nextInfluencers); setProducts(nextProducts); setProjects(nextProjects);
    } catch (err: any) { setError(err.message || 'Failed loading influencer studio'); }
  }, [token]);

  useEffect(() => { void load(); }, [load]);

  const refreshProject = async (id: string) => { const project = await api.getInfluencerProject(id); setSelectedProject(project); await load(); return project; };

  const generateInfluencer = async (influencer: Influencer, variations: number) => {
    setError(''); setGeneratingFor(influencer.id); setImageOwner(influencer.id); setImages([]);
    try {
      const prepared = await api.getInfluencerGenerationPrompt(influencer.id);
      const result = await api.generate({ workflow: 'text-to-image', model: 'google/nano-banana-2', prompt: prepared.prompt, params: { aspect_ratio: '3:4', resolution: '1K', output_format: 'jpg', variations, reference_image_ids: prepared.reference_storage_ids } });
      const pending: GeneratedImage[] = result.predictions || [{ id: result.id, status: result.status, output_url: result.output_url }];
      setImages(pending);
      const complete = await Promise.all(pending.map(async (item) => {
        let current = item;
        for (let attempt = 0; attempt < 90 && !['succeeded', 'failed', 'canceled'].includes(current.status); attempt += 1) {
          await new Promise((resolve) => window.setTimeout(resolve, 2500));
          current = await api.getPrediction(item.id);
          setImages((existing) => existing.map((image) => image.id === item.id ? current : image));
        }
        return current;
      }));
      setImages(complete);
    } catch (err: any) { setError(err.message || 'Influencer generation failed'); } finally { setGeneratingFor(null); }
  };

  const approveImage = async (influencerId: string, predictionId: string) => {
    setBusy('approve-image'); setError('');
    try { await api.approveInfluencer(influencerId, predictionId); setImages([]); setImageOwner(null); await load(); }
    catch (err: any) { setError(err.message || 'Failed approving influencer'); }
    finally { setBusy(''); }
  };

  if (!token) return <div className="glass-card" style={{ padding: '4rem', textAlign: 'center' }}>Sign in to create AI influencers.</div>;

  return <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
    <section className="glass-card" style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}>
      <div><span className="badge badge-purple">Guided workflow</span><h1 style={{ margin: '0.55rem 0 0.35rem' }}>AI Influencer Studio</h1><p style={{ margin: 0, color: 'var(--foreground-muted)' }}>Create an original or creator-referenced influencer, plan every scene, then direct one consistent Kling V3 video.</p></div>
      <div style={{ display: 'flex', gap: '0.5rem' }}>{(['influencers', 'products', 'projects'] as Tab[]).map((item) => <button key={item} className={`btn ${tab === item ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    </section>
    {error && <div style={{ padding: '0.8rem', color: '#f87171', border: '1px solid rgba(248,113,113,.35)', borderRadius: 10 }}>{error}</div>}
    {tab === 'influencers' && <InfluencersPanel influencers={influencers} images={images} imageOwner={imageOwner} generatingFor={generatingFor} busy={busy} onCreated={load} onGenerate={generateInfluencer} onApprove={approveImage} setError={setError} />}
    {tab === 'products' && <ProductsPanel products={products} onCreated={load} setError={setError} />}
    {tab === 'projects' && <ProjectsPanel projects={projects} influencers={influencers} products={products} selected={selectedProject} setSelected={setSelectedProject} refresh={refreshProject} onCreated={load} busy={busy} setBusy={setBusy} setError={setError} />}
  </div>;
}

function InfluencersPanel({ influencers, images, imageOwner, generatingFor, busy, onCreated, onGenerate, onApprove, setError }: any) {
  const [form, setForm] = useState({ name: '', age: 25, gender: 'woman', niche: 'lifestyle', personality: 'warm, confident and energetic', appearance: '', wardrobe: 'modern casual', visual: 'premium photorealistic UGC', voice: 'warm, conversational Canadian English' });
  const [referenceFiles, setReferenceFiles] = useState<File[]>([]); const [referenceConsent, setReferenceConsent] = useState(false); const [uploading, setUploading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setUploading(true); setError(''); try { const uploads = []; for (const file of referenceFiles.slice(0, 4)) uploads.push(await api.uploadFile(file, 'influencer-identity-reference')); await api.createInfluencer({ name: form.name, voice_profile: form.voice, reference_storage_ids: uploads.map((item) => item.id), reference_consent: referenceFiles.length ? referenceConsent : false, profile: { age: Number(form.age), gender_presentation: form.gender, content_niche: form.niche, personality: form.personality, appearance: form.appearance, default_wardrobe: form.wardrobe, visual_style: form.visual } }); setForm({ ...form, name: '', appearance: '' }); setReferenceFiles([]); setReferenceConsent(false); await onCreated(); } catch (err: any) { setError(err.message || 'Failed creating influencer'); } finally { setUploading(false); } };
  return <div className="influencer-split" style={{ display: 'grid', gridTemplateColumns: 'minmax(280px, 380px) 1fr', gap: '1.25rem' }}>
    <form className="glass-card" onSubmit={submit} style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}><h2 style={{ margin: 0 }}>Create influencer</h2><p style={{ margin: 0, color: 'var(--foreground-muted)', fontSize: '.82rem' }}>Create an original adult identity or guide it with photos you have permission to use.</p>
      <label style={field}>Name<input className="form-input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>
      <div style={grid}><label style={field}>Age<input className="form-input" type="number" min={18} max={80} value={form.age} onChange={(e) => setForm({ ...form, age: Number(e.target.value) })} /></label><label style={field}>Gender presentation<input className="form-input" value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })} /></label></div>
      <label style={field}>Content niche<input className="form-input" value={form.niche} onChange={(e) => setForm({ ...form, niche: e.target.value })} /></label><label style={field}>Personality<input className="form-input" value={form.personality} onChange={(e) => setForm({ ...form, personality: e.target.value })} /></label>
      <label style={field}>Appearance<textarea className="form-textarea" required rows={4} placeholder="Face, complexion, hair, build, distinguishing features..." value={form.appearance} onChange={(e) => setForm({ ...form, appearance: e.target.value })} /></label>
      <label style={field}>Default wardrobe<input className="form-input" value={form.wardrobe} onChange={(e) => setForm({ ...form, wardrobe: e.target.value })} /></label><label style={field}>Visual style<input className="form-input" value={form.visual} onChange={(e) => setForm({ ...form, visual: e.target.value })} /></label><label style={field}>Voice profile<input className="form-input" value={form.voice} onChange={(e) => setForm({ ...form, voice: e.target.value })} /></label>
      <label style={field}>Optional creator reference images (up to 4)<input type="file" accept="image/*" multiple onChange={(e) => setReferenceFiles(Array.from(e.target.files || []).slice(0, 4))} /></label>
      {referenceFiles.length > 0 && <label style={{ ...field, flexDirection: 'row', alignItems: 'flex-start' }}><input type="checkbox" checked={referenceConsent} onChange={(e) => setReferenceConsent(e.target.checked)} /><span>I confirm every depicted person is 18+, I have permission to use these images, and I will not use them for deceptive impersonation.</span></label>}
      <button className="btn btn-primary" type="submit" disabled={uploading || (referenceFiles.length > 0 && !referenceConsent)}>{uploading ? 'Uploading references…' : 'Save draft'}</button>
    </form>
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>{influencers.map((item: Influencer) => <article key={item.id} className="glass-card"><div style={{ display: 'flex', gap: '1rem' }}>{item.versions?.[0]?.imageUrl && <img src={item.versions[0].imageUrl} alt={item.name} style={{ width: 110, height: 140, objectFit: 'cover', borderRadius: 12 }} />}<div style={{ flex: 1 }}><span className="badge badge-purple">{item.status}</span><h3>{item.name}</h3><p style={{ color: 'var(--foreground-muted)', fontSize: '.85rem' }}>{item.profile?.content_niche} · age {item.profile?.age} · version {item.currentVersion}</p><div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}><button className="btn btn-primary" disabled={generatingFor === item.id} onClick={() => onGenerate(item, 1)}>Generate primary · 1 credit</button><button className="btn btn-secondary" disabled={generatingFor === item.id} onClick={() => onGenerate(item, 4)}>4 variations · 4 credits</button></div></div></div>
        {generatingFor === item.id && <p style={{ color: 'var(--foreground-muted)' }}>Generating portraits…</p>}
        {images.length > 0 && imageOwner === item.id && <div style={{ ...grid, marginTop: '1rem' }}>{images.map((image: GeneratedImage) => <div key={image.id}>{image.output_url ? <img src={image.output_url} alt="Generated influencer option" style={{ width: '100%', aspectRatio: '3/4', objectFit: 'cover', borderRadius: 12 }} /> : <div style={{ padding: '2rem' }}>{image.status}</div>}<button className="btn btn-primary" style={{ width: '100%', marginTop: '.4rem' }} disabled={image.status !== 'succeeded' || busy} onClick={() => onApprove(item.id, image.id)}>Use this appearance</button></div>)}</div>}
      </article>)}{influencers.length === 0 && <div className="glass-card">No influencers yet. Create your first fictional creator.</div>}</div>
  </div>;
}

function ProductsPanel(props: any) {
  return <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}><ProductUrlScanner {...props} /><LegacyProductsPanel {...props} /></div>;
}

function ProductUrlScanner({ onCreated, setError }: any) {
  const [url, setUrl] = useState(''); const [scanning, setScanning] = useState(false); const [saving, setSaving] = useState(false); const [scan, setScan] = useState<any>(null);
  const run = async () => { setScanning(true); setError(''); try { setScan(await api.scanInfluencerProductUrl(url)); } catch (err: any) { setError(err.message || 'Failed scanning product URL'); } finally { setScanning(false); } };
  const save = async () => { if (!scan) return; setSaving(true); setError(''); try { await api.createInfluencerProduct({ name: scan.name, brand_name: scan.brand_name, description: scan.description, approved_claims: scan.detected_claims, restricted_claims: scan.restrictions_to_review, brand_colours: scan.brand_colours, source_url: scan.source_url, source_data: scan, external_image_urls: scan.image_urls, reference_storage_ids: [] }); setScan(null); setUrl(''); await onCreated(); } catch (err: any) { setError(err.message || 'Failed saving scanned product'); } finally { setSaving(false); } };
  return <section className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '.8rem' }}><div><span className="badge badge-purple">URL scanner</span><h2>Import a product page</h2><p style={{ color: 'var(--foreground-muted)', marginBottom: 0 }}>Pull structured product data from a public HTTPS page. Review all extracted claims before saving.</p></div><div style={{ display: 'flex', gap: '.6rem', flexWrap: 'wrap' }}><input className="form-input" type="url" placeholder="https://brand.example/products/product-name" value={url} onChange={(event) => setUrl(event.target.value)} style={{ flex: '1 1 320px' }} /><button className="btn btn-primary" disabled={scanning || !url.trim()} onClick={run}>{scanning ? 'Scanning…' : 'Scan product URL'}</button></div>
    {scan && <div style={{ display: 'flex', flexDirection: 'column', gap: '.75rem', borderTop: '1px solid var(--panel-border)', paddingTop: '.9rem' }}><div style={grid}><label style={field}>Product name<input className="form-input" value={scan.name} onChange={(e) => setScan({ ...scan, name: e.target.value })} /></label><label style={field}>Brand<input className="form-input" value={scan.brand_name} onChange={(e) => setScan({ ...scan, brand_name: e.target.value })} /></label><label style={field}>Category<input className="form-input" value={scan.category} onChange={(e) => setScan({ ...scan, category: e.target.value })} /></label></div><label style={field}>Description<textarea className="form-textarea" rows={4} value={scan.description} onChange={(e) => setScan({ ...scan, description: e.target.value })} /></label><label style={field}>Detected claims requiring approval<textarea className="form-textarea" rows={4} value={(scan.detected_claims || []).join('\n')} onChange={(e) => setScan({ ...scan, detected_claims: e.target.value.split('\n').filter(Boolean) })} /></label><label style={field}>Restrictions to review<textarea className="form-textarea" rows={3} value={(scan.restrictions_to_review || []).join('\n')} onChange={(e) => setScan({ ...scan, restrictions_to_review: e.target.value.split('\n').filter(Boolean) })} /></label>{scan.image_urls?.length > 0 && <div><strong>Source images</strong><p style={{ color: 'var(--foreground-muted)', fontSize: '.75rem' }}>Preview only. Upload approved originals below to use them as durable generation references.</p><div style={grid}>{scan.image_urls.map((imageUrl: string) => <img key={imageUrl} src={imageUrl} alt="Scanned product" referrerPolicy="no-referrer" style={{ width: '100%', maxHeight: 220, objectFit: 'contain', borderRadius: 10, background: '#fff' }} />)}</div></div>}<button className="btn btn-primary" disabled={saving || !scan.name?.trim()} onClick={save}>{saving ? 'Saving…' : 'Save reviewed product'}</button></div>}
  </section>;
}

function LegacyProductsPanel({ products, onCreated, setError }: any) {
  const [form, setForm] = useState({ name: '', brand: '', description: '', approved: '', restricted: '', colours: '' }); const [files, setFiles] = useState<File[]>([]); const [uploading, setUploading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setUploading(true); try { const uploads = []; for (const file of files.slice(0, 8)) uploads.push(await api.uploadFile(file, 'influencer-product-reference')); await api.createInfluencerProduct({ name: form.name, brand_name: form.brand, description: form.description, approved_claims: form.approved.split('\n'), restricted_claims: form.restricted.split('\n'), brand_colours: form.colours.split(',').map((x) => x.trim()), reference_storage_ids: uploads.map((x) => x.id) }); setForm({ name: '', brand: '', description: '', approved: '', restricted: '', colours: '' }); setFiles([]); await onCreated(); } catch (err: any) { setError(err.message); } finally { setUploading(false); } };
  return <div style={{ display: 'grid', gridTemplateColumns: 'minmax(280px, 400px) 1fr', gap: '1.25rem' }}><form className="glass-card" onSubmit={submit} style={{ display: 'flex', flexDirection: 'column', gap: '.8rem' }}><h2 style={{ margin: 0 }}>Add product</h2><label style={field}>Product name<input required className="form-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label style={field}>Brand<input className="form-input" value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} /></label><label style={field}>Description<textarea className="form-textarea" rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label style={field}>Approved claims, one per line<textarea className="form-textarea" rows={3} value={form.approved} onChange={(e) => setForm({ ...form, approved: e.target.value })} /></label><label style={field}>Restricted claims, one per line<textarea className="form-textarea" rows={3} value={form.restricted} onChange={(e) => setForm({ ...form, restricted: e.target.value })} /></label><label style={field}>Brand colours<input className="form-input" value={form.colours} onChange={(e) => setForm({ ...form, colours: e.target.value })} /></label><label style={field}>Reference images<input type="file" accept="image/*" multiple onChange={(e) => setFiles(Array.from(e.target.files || []))} /></label><button className="btn btn-primary" disabled={uploading}>{uploading ? 'Uploading…' : 'Save product'}</button></form><div style={grid}>{products.map((product: Product) => <article className="glass-card" key={product.id}><span className="badge badge-purple">Product</span><h3>{product.name}</h3><p>{product.brandName || 'Independent brand'}</p><p style={{ color: 'var(--foreground-muted)' }}>{product.description}</p></article>)}</div></div>;
}

function ProjectsPanel({ projects, influencers, products, selected, setSelected, refresh, onCreated, busy, setBusy, setError }: any) {
  const approved = influencers.filter((item: Influencer) => item.status === 'approved'); const [form, setForm] = useState({ title: '', idea: '', influencer: '', product: '', duration: 15, aspect: '9:16', platform: 'TikTok', format: 'UGC advertisement', objective: 'Drive consideration', audience: '', cta: '', dialogue: 'Natural dialogue and voiceover' });
  const create = async (event: FormEvent) => { event.preventDefault(); try { const created = await api.createInfluencerProject({ title: form.title, idea: form.idea, influencer_id: form.influencer, product_id: form.product || undefined, duration_seconds: Number(form.duration), aspect_ratio: form.aspect, brief: { target_platform: form.platform, content_format: form.format, objective: form.objective, target_audience: form.audience, call_to_action: form.cta, dialogue_preference: form.dialogue } }); await onCreated(); setSelected(await api.getInfluencerProject(created.id)); } catch (err: any) { setError(err.message); } };
  const open = async (id: string) => { try { setSelected(await api.getInfluencerProject(id)); } catch (err: any) { setError(err.message); } };
  const plan = async () => { if (!selected) return; setBusy('plan'); try { setSelected(await api.planInfluencerProject(selected.id)); await onCreated(); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  return <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: '1.25rem' }}><aside style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}><form className="glass-card" onSubmit={create} style={{ display: 'flex', flexDirection: 'column', gap: '.7rem' }}><h2 style={{ margin: 0 }}>New video project</h2><label style={field}>Title<input required className="form-input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label style={field}>Influencer<select required className="form-select" value={form.influencer} onChange={(e) => setForm({ ...form, influencer: e.target.value })}><option value="">Choose approved influencer</option>{approved.map((item: Influencer) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label style={field}>Product<select className="form-select" value={form.product} onChange={(e) => setForm({ ...form, product: e.target.value })}><option value="">No product</option>{products.map((item: Product) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label style={field}>Video idea<textarea required className="form-textarea" rows={5} value={form.idea} onChange={(e) => setForm({ ...form, idea: e.target.value })} /></label><div style={grid}><label style={field}>Duration<select className="form-select" value={form.duration} onChange={(e) => setForm({ ...form, duration: Number(e.target.value) })}><option value={5}>5 sec</option><option value={10}>10 sec</option><option value={15}>15 sec</option></select></label><label style={field}>Frame<select className="form-select" value={form.aspect} onChange={(e) => setForm({ ...form, aspect: e.target.value })}><option>9:16</option><option>16:9</option><option>1:1</option></select></label></div><label style={field}>Platform<input className="form-input" value={form.platform} onChange={(e) => setForm({ ...form, platform: e.target.value })} /></label><label style={field}>Format<input className="form-input" value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value })} /></label><label style={field}>Audience<input className="form-input" value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })} /></label><label style={field}>Call to action<input className="form-input" value={form.cta} onChange={(e) => setForm({ ...form, cta: e.target.value })} /></label><button className="btn btn-primary" disabled={!approved.length}>Create project</button></form><div className="glass-card"><h3>Projects</h3>{projects.map((item: Project) => <button key={item.id} className={`btn ${selected?.id === item.id ? 'btn-primary' : 'btn-secondary'}`} style={{ width: '100%', marginBottom: '.5rem', textAlign: 'left' }} onClick={() => open(item.id)}>{item.title}<small style={{ display: 'block' }}>{item.status} · {item._count?.scenes || 0} scenes</small></button>)}</div></aside>
    <main>{selected ? <ProjectEditor project={selected} setProject={setSelected} refresh={refresh} plan={plan} busy={busy} setBusy={setBusy} setError={setError} /> : <div className="glass-card" style={{ padding: '4rem', textAlign: 'center' }}>Create or select an influencer video project.</div>}</main></div>;
}

function ProjectEditor({ project, setProject, refresh, plan, busy, setBusy, setError }: any) {
  const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState<any>({}); const [rewrite, setRewrite] = useState('');
  const edit = (scene: Scene) => { setEditing(scene.id); setDraft({ ...scene, duration_seconds: scene.durationSeconds, character_action: scene.characterAction, camera_framing: scene.cameraFraming, camera_movement: scene.cameraMovement, product_visible: scene.productVisible, on_screen_text: scene.onScreenText || '' }); };
  const save = async (sceneId: string) => { setBusy('save'); try { setProject(await api.updateInfluencerScene(project.id, sceneId, draft)); setEditing(null); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const rewriteScene = async (sceneId: string) => { setBusy('rewrite'); try { setProject(await api.rewriteInfluencerScene(project.id, sceneId, rewrite)); setRewrite(''); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const approve = async () => { setBusy('approve-scenes'); try { setProject(await api.approveInfluencerScenes(project.id)); await refresh(project.id); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const add = async () => { setBusy('scene-action'); try { setProject(await api.addInfluencerScene(project.id, { title: `Scene ${(project.scenes?.length || 0) + 1}`, duration_seconds: 1, location: 'To be defined', description: 'Describe this scene.', character_action: 'Define the influencer action.', expression: 'Natural', wardrobe: project.scenes?.[project.scenes.length - 1]?.wardrobe || 'Default wardrobe', camera_framing: 'Medium shot', camera_movement: 'Static', lighting: 'Natural light', product_visible: false, dialogue: '', voiceover: '', on_screen_text: '', transition: 'Cut' })); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const duplicateProject = async () => { setBusy('project-duplicate'); try { const copy = await api.duplicateInfluencerProject(project.id); setProject(copy); await refresh(copy.id); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const duplicate = async (sceneId: string) => { setBusy('scene-action'); try { setProject(await api.duplicateInfluencerScene(project.id, sceneId)); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const remove = async (sceneId: string) => { setBusy('scene-action'); try { setProject(await api.deleteInfluencerScene(project.id, sceneId)); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const move = async (index: number, direction: number) => { const ordered = [...(project.scenes || [])]; const target = index + direction; if (target < 0 || target >= ordered.length) return; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; setBusy('scene-action'); try { setProject(await api.reorderInfluencerScenes(project.id, ordered.map((scene: Scene) => scene.id))); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  const keys = [{ k: 'location', l: 'Location' }, { k: 'description', l: 'Description' }, { k: 'character_action', l: 'Action' }, { k: 'expression', l: 'Expression' }, { k: 'wardrobe', l: 'Wardrobe' }, { k: 'camera_framing', l: 'Camera framing' }, { k: 'camera_movement', l: 'Camera movement' }, { k: 'lighting', l: 'Lighting' }, { k: 'dialogue', l: 'Dialogue' }, { k: 'voiceover', l: 'Voiceover' }, { k: 'on_screen_text', l: 'On-screen text' }, { k: 'transition', l: 'Transition' }];
  return <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}><section className="glass-card"><span className="badge badge-purple">{project.status}</span><h2>{project.title}</h2><p>{project.idea}</p><div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}><span className="badge badge-purple">{project.durationSeconds} seconds</span><span className="badge badge-purple">{project.aspectRatio}</span><button className="btn btn-primary" disabled={busy === 'plan'} onClick={plan}>{project.scenes?.length ? 'Regenerate free scene plan' : 'Generate free scene plan'}</button>{project.scenes?.length > 0 && <button className="btn btn-secondary" disabled={busy} onClick={approve}>Approve scene plan</button>}<button className="btn btn-secondary" disabled={Boolean(busy)} onClick={duplicateProject}>Create variation</button>{project.scenes?.length > 0 && project.scenes.length < 6 && <button className="btn btn-secondary" disabled={Boolean(busy)} onClick={add}>Add scene</button>}</div></section>
    {project.scenes?.length > 0 && <section className="glass-card"><strong>Scene order and copies</strong><div style={{ display: 'flex', flexDirection: 'column', gap: '.45rem', marginTop: '.7rem' }}>{project.scenes.map((scene: Scene, index: number) => <div key={scene.id} style={{ display: 'flex', alignItems: 'center', gap: '.4rem', flexWrap: 'wrap' }}><span style={{ flex: 1, minWidth: 150 }}>{index + 1}. {scene.title}</span><button className="btn btn-secondary" disabled={index === 0 || busy} onClick={() => move(index, -1)}>Up</button><button className="btn btn-secondary" disabled={index === project.scenes.length - 1 || busy} onClick={() => move(index, 1)}>Down</button><button className="btn btn-secondary" disabled={project.scenes.length >= 6 || busy} onClick={() => duplicate(scene.id)}>Duplicate</button><button className="btn btn-secondary" disabled={project.scenes.length <= 2 || busy} onClick={() => remove(scene.id)}>Delete</button></div>)}</div></section>}
    {project.scenes?.map((scene: Scene) => <article key={scene.id} className="glass-card"><div style={{ display: 'flex', justifyContent: 'space-between' }}><div><span className="badge badge-purple">Scene {scene.index + 1} · {scene.durationSeconds}s</span><h3>{scene.title}</h3></div><button className="btn btn-secondary" onClick={() => editing === scene.id ? setEditing(null) : edit(scene)}>{editing === scene.id ? 'Cancel' : 'Edit scene'}</button></div>{editing === scene.id ? <div style={{ display: 'flex', flexDirection: 'column', gap: '.7rem' }}><div style={grid}><label style={field}>Title<input className="form-input" value={draft.title || ''} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label style={field}>Duration<input className="form-input" type="number" min={1} value={draft.duration_seconds} onChange={(e) => setDraft({ ...draft, duration_seconds: Number(e.target.value) })} /></label></div>{keys.map(({ k, l }) => <label key={k} style={field}>{l}<textarea className="form-textarea" rows={k === 'description' || k === 'character_action' ? 3 : 2} value={draft[k] || ''} onChange={(e) => setDraft({ ...draft, [k]: e.target.value })} /></label>)}<label style={field}><span><input type="checkbox" checked={Boolean(draft.product_visible)} onChange={(e) => setDraft({ ...draft, product_visible: e.target.checked })} /> Product visible</span></label><button className="btn btn-primary" onClick={() => save(scene.id)}>Save scene</button></div> : <><p>{scene.description}</p><div style={grid}><small><strong>Action</strong><br />{scene.characterAction}</small><small><strong>Camera</strong><br />{scene.cameraFraming} · {scene.cameraMovement}</small><small><strong>Location</strong><br />{scene.location}</small><small><strong>Wardrobe</strong><br />{scene.wardrobe}</small></div><div style={{ display: 'flex', gap: '.5rem', marginTop: '1rem' }}><input className="form-input" placeholder="Rewrite: make the hook stronger..." value={rewrite} onChange={(e) => setRewrite(e.target.value)} /><button className="btn btn-secondary" disabled={!rewrite.trim() || busy === 'rewrite'} onClick={() => rewriteScene(scene.id)}>AI rewrite · free</button></div></>}</article>)}
    {['scenes_approved', 'storyboard_ready', 'storyboard_approved', 'video_ready'].includes(project.status) && <StoryboardStudio project={project} setProject={setProject} setBusy={setBusy} busy={busy} setError={setError} />}
    {['storyboard_approved', 'video_ready'].includes(project.status) && <VideoStudio project={project} setProject={setProject} setBusy={setBusy} busy={busy} setError={setError} />}</div>;
}

function StoryboardStudio({ project, setProject, setBusy, busy, setError }: any) {
  const [style, setStyle] = useState('photorealistic premium UGC, natural smartphone cinematography, realistic skin and believable environments');
  const [consistency, setConsistency] = useState('Prioritize exact facial identity, wardrobe continuity and accurate product packaging.');
  const [progress, setProgress] = useState('');

  const generate = async () => {
    setBusy('storyboard'); setError(''); setProgress('Preparing storyboard prompt…');
    try {
      const prepared = await api.prepareInfluencerStoryboard(project.id, { visual_style: style, consistency_instruction: consistency });
      setProgress('Nano Banana 2 is generating one unified storyboard…');
      const submitted = await api.generate({ workflow: prepared.generation.workflow, model: prepared.generation.model, prompt: prepared.prompt, params: { ...prepared.generation.params, reference_image_ids: prepared.reference_storage_ids } });
      let result = await api.getPrediction(submitted.id);
      for (let attempt = 0; attempt < 90 && !['succeeded', 'failed', 'canceled'].includes(result.status); attempt += 1) {
        await new Promise((resolve) => window.setTimeout(resolve, 2500)); result = await api.getPrediction(submitted.id);
      }
      if (result.status !== 'succeeded') throw new Error(result.error || 'Storyboard generation did not complete');
      setProgress('Saving immutable storyboard version…');
      await api.saveInfluencerStoryboard(project.id, { prediction_id: submitted.id, prompt: prepared.prompt, layout: prepared.layout, visual_style: prepared.visual_style, reference_storage_ids: prepared.reference_storage_ids, scenes_revision: prepared.scenes_revision });
      setProject(await api.getInfluencerProject(project.id)); setProgress('');
    } catch (err: any) { setError(err.message || 'Storyboard generation failed'); setProgress(''); } finally { setBusy(''); }
  };

  const approve = async (id: string) => { setBusy('storyboard-approve'); try { setProject(await api.approveInfluencerStoryboard(project.id, id)); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  return <section className="glass-card" style={{ borderColor: 'rgba(139,92,246,.5)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', flexWrap: 'wrap' }}><div><span className="badge badge-purple">Storyboard</span><h3>Unified visual blueprint</h3><p style={{ color: 'var(--foreground-muted)', maxWidth: 720 }}>One image contains every approved scene and becomes Kling V3’s primary visual reference. Regeneration always creates a new version.</p></div><button className="btn btn-primary" disabled={Boolean(busy)} onClick={generate}>{project.storyboards?.length ? 'Generate new version · 1 credit' : 'Generate storyboard · 1 credit'}</button></div>
    <div style={grid}><label style={field}>Visual style<input className="form-input" value={style} onChange={(e) => setStyle(e.target.value)} /></label><label style={field}>Consistency instruction<input className="form-input" value={consistency} onChange={(e) => setConsistency(e.target.value)} /></label></div>{progress && <p style={{ color: '#c4b5fd' }}>{progress}</p>}
    {project.storyboards?.length > 0 && <div style={{ ...grid, marginTop: '1rem' }}>{project.storyboards.map((board: Storyboard) => { const stale = board.scenesRevision !== project.scenesRevision; return <article key={board.id} style={{ border: `1px solid ${board.approved ? '#8b5cf6' : 'var(--panel-border)'}`, borderRadius: 14, padding: '.75rem', background: 'rgba(255,255,255,.02)' }}><img src={board.imageUrl} alt={`Storyboard version ${board.version}`} style={{ width: '100%', maxHeight: 520, objectFit: 'contain', borderRadius: 10, background: '#050505' }} /><div style={{ display: 'flex', justifyContent: 'space-between', gap: '.5rem', alignItems: 'center', marginTop: '.7rem' }}><div><strong>Version {board.version}</strong><small style={{ display: 'block', color: 'var(--foreground-muted)' }}>{board.layout} · {stale ? 'older scene revision' : board.approved ? 'approved' : 'ready'}</small></div><button className="btn btn-secondary" disabled={stale || board.approved || Boolean(busy)} onClick={() => approve(board.id)}>{board.approved ? 'Selected' : 'Approve'}</button></div><details style={{ marginTop: '.6rem' }}><summary>Generation details</summary><p style={{ fontSize: '.72rem', color: 'var(--foreground-muted)' }}>{board.visualStyle}</p><pre style={{ whiteSpace: 'pre-wrap', fontSize: '.68rem', color: 'var(--foreground-muted)' }}>{board.prompt}</pre></details></article>; })}</div>}
  </section>;
}

function VideoStudio({ project, setProject, setBusy, busy, setError }: any) {
  const [motion, setMotion] = useState('Use natural human movement, confident social pacing, smooth motivated camera motion and clean transitions.');
  const [progress, setProgress] = useState('');
  const renderCredits = Math.ceil(project.durationSeconds * 50 / 15);
  const generate = async () => {
    setBusy('video'); setError(''); setProgress('Preparing storyboard, identity and product references for Kling V3…');
    try {
      const prepared = await api.prepareInfluencerVideo(project.id, { motion_instructions: motion });
      setProgress(`Generating ${project.durationSeconds}-second video with synchronized audio…`);
      const submitted = await api.generate({ workflow: prepared.generation.workflow, model: prepared.generation.model, prompt: prepared.prompt, params: { ...prepared.generation.params, reference_image_ids: prepared.reference_storage_ids } });
      let result = await api.getPrediction(submitted.id);
      for (let attempt = 0; attempt < 150 && !['succeeded', 'failed', 'canceled'].includes(result.status); attempt += 1) {
        await new Promise((resolve) => window.setTimeout(resolve, 3000)); result = await api.getPrediction(submitted.id);
      }
      if (result.status !== 'succeeded') throw new Error(result.error || 'Kling V3 generation did not complete');
      setProgress('Saving video attempt…');
      await api.saveInfluencerVideo(project.id, { prediction_id: submitted.id, storyboard_id: prepared.storyboard_id, prompt: prepared.prompt, motion_instructions: prepared.motion_instructions, settings: prepared.generation.params });
      setProject(await api.getInfluencerProject(project.id)); setProgress('');
    } catch (err: any) { setError(err.message || 'Video generation failed'); setProgress(''); } finally { setBusy(''); }
  };
  const approve = async (id: string) => { setBusy('video-approve'); try { setProject(await api.approveInfluencerVideo(project.id, id)); } catch (err: any) { setError(err.message); } finally { setBusy(''); } };
  return <section className="glass-card" style={{ borderColor: 'rgba(34,197,94,.4)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'flex-start', flexWrap: 'wrap' }}><div><span className="badge badge-purple">Final video</span><h3>Kling V3 production</h3><p style={{ color: 'var(--foreground-muted)', maxWidth: 700 }}>The approved storyboard remains unchanged. Every regeneration creates a separate Kling V3 attempt with generated speech, voiceover, ambience and sound. Pricing scales with duration up to 50 credits for 15 seconds.</p></div><button className="btn btn-primary" disabled={Boolean(busy)} onClick={generate}>{project.videoGenerations?.length ? `Regenerate · ${renderCredits} credits` : `Generate final video · ${renderCredits} credits`}</button></div><label style={field}>Motion and performance instructions<textarea className="form-textarea" rows={3} value={motion} onChange={(e) => setMotion(e.target.value)} /></label>{progress && <p style={{ color: '#86efac' }}>{progress}</p>}
    {project.videoGenerations?.length > 0 && <div style={{ ...grid, marginTop: '1rem' }}>{project.videoGenerations.map((video: VideoGeneration) => <article key={video.id} style={{ border: `1px solid ${video.approved ? '#22c55e' : 'var(--panel-border)'}`, borderRadius: 14, padding: '.75rem', background: 'rgba(255,255,255,.02)' }}><video src={video.videoUrl} controls playsInline style={{ width: '100%', maxHeight: 560, borderRadius: 10, background: '#000' }} /><div style={{ display: 'flex', justifyContent: 'space-between', gap: '.6rem', marginTop: '.7rem', flexWrap: 'wrap' }}><div><strong>Attempt {video.attempt}</strong><small style={{ display: 'block', color: 'var(--foreground-muted)' }}>{video.creditsUsed} credits · {video.approved ? 'approved' : 'ready for review'}</small></div><div style={{ display: 'flex', gap: '.4rem' }}><a className="btn btn-secondary" href={video.videoUrl} download target="_blank" rel="noopener noreferrer">Download</a><button className="btn btn-primary" disabled={video.approved || Boolean(busy)} onClick={() => approve(video.id)}>{video.approved ? 'Approved' : 'Approve video'}</button></div></div><details style={{ marginTop: '.6rem' }}><summary>Prompt and settings</summary><p style={{ color: 'var(--foreground-muted)', fontSize: '.72rem' }}>{video.motionInstructions}</p><pre style={{ whiteSpace: 'pre-wrap', color: 'var(--foreground-muted)', fontSize: '.68rem' }}>{video.prompt}</pre></details></article>)}</div>}
  </section>;
}
